### ISSUE TITLE
Print first 5 rows of a csv file

### ISSUE THREAD

**Issue by abhi8893** [anu-coder/Basics-of-Python#8]
Download the attached CSV file [Favorite TV Shows - Form Responses 1.zip](https://github.com/anu-coder/Basics-of-Python/files/6177139/Favorite.TV.Shows.-.Form.Responses.1.zip). 

Write a python program with the following behavior:

```
$ python read_csv_file.py 
Enter the CSV file path: <Enter path here> data/Favorite TV Shows - Form Responses 1.csv

The headers of the file are:  
1. Timestamp
2. title
3. genres

Choose a header: <USER ENTERS AN OPTION NUMBER> 2
Max rows to display: <USER ENTERS A NUMBER> 5

title
-----
Dynasty
The Office
Blindspot
24
Friends

```

Steps:
1. Ask for a CSV file
2. Print out the headers
3. Ask which header to display
4. Ask the maximum number of rows to display
5. Display the information in a pretty format

Don't use `pandas`. Use python's `csv` module to write this program.

**Comment by anu-coder** [comment]
Thank you for this nice question.

Have committed the first part. 
But getting an extra `none` while printing the headers.

```
The headers of the file are:  
1. Timestamp
2. title
3. genres
None
```
Check the branch `feature-2` for details.

**Comment by abhi8893** [comment]
https://github.com/anu-coder/Basics-of-Python/blob/38550f49a8d8b80d47c3a0e4e839613703ae55fe/scripts/problem_csv.py#L13-L17

Why `None` is bring printed?
Because in Line 15.

```python
print(read_csv_file(path))
```
 you are printing the return value of the `read_csv_file` function which has no return statement. In Python, if a function has no **explicit** return statement, it will default to returning `None`.

Also, I notice in your comment, you have the line `The headers of the file are:`. But this line is nowhere being printed in your code?

**Comment by abhi8893** [comment]
In Line 20: 

https://github.com/anu-coder/Basics-of-Python/blob/ea9cd705e0ec940438cf0da8442be0c764ae5346/scripts/read_csv_file.py#L19-L21

add r to make it a raw string to avoid problem with backslashes as follows:
```python
    path = r'..\data\Favorite TV Shows - Form Responses 1.csv'
```

In Lines 26 and 27:

https://github.com/anu-coder/Basics-of-Python/blob/ea9cd705e0ec940438cf0da8442be0c764ae5346/scripts/read_csv_file.py#L24-L28

convert the input received to ```int``` as follows:

```python
    col_choice = int(input("Choose a header: "))
    max_rows = int(input("Max rows to display: "))
```

**Comment by anu-coder** [comment]
Thank you @abhi8893 

I have now completed the task:
Please check `feature_2`

The `output` obtained is as follows:

```
The headers of the file are: 
1. Timestamp
2. title
3. genres
Choose a header: 2
Max rows to display: 5


title
----------
Dynasty
The Office
Blindspot
24
Friends
```

**Comment by abhi8893** [comment]
Just a minor detail on the dashes added:

Actual output: Dashes spill over
```
title
----------
```

Desired output: Dashes match the length of the column

```
title
-----
```

See if you can print as many dashes ```-``` as the characters in the selected column?

**Comment by anu-coder** [comment]
umm haha!
Implemented the same @abhi8893 

:)

```
The headers of the file are:
1. Timestamp
2. title
3. genres
Choose a header: 2
Max rows to display: 3


title
-----
Dynasty
The Office
Blindspot
```

check out `feature_2`
